---
- name: Check Docker version on all servers
  hosts: all
  gather_facts: no

  tasks:
    - name: Check Docker version
      ansible.builtin.command: docker --version
      register: docker_version_output
      ignore_errors: yes

    - name: Display Docker version output
      ansible.builtin.debug:
        var: docker_version_output.stdout